
name: 'terascan'
description: ''
author: 'Paul Kelleher'
inputs:
  action:
    required: true
    
runs:
  using: "composite"
  steps:
    - id: terascan
      run: |
        curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz 
        tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz
        install terrascan /usr/local/bin && rm terrascan
        terrascan --help
      shell: bash
branding:
  icon: 'cloud'
  color: 'gray-dark'
